apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lite-llm-customer
  namespace: argocd
spec:
  project: application
  source:
    repoURL: https://github.com/ADORSYS-GIS/ai-helm
    targetRevision: HEAD
    path: charts/lite-llm-customer
  destination:
    server: https://kubernetes.default.svc
    namespace: lite-llm-customer
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2
